// @vitest-environment jsdom
import {beforeEach,afterEach,describe,it,expect,vi} from 'vitest';
import {cleanup,render,screen,fireEvent,waitFor} from '@testing-library/react';
import type {Snapshot,Settings} from './types';
import App from './App';
const mock=vi.hoisted(()=>({invoke:vi.fn(),snapshot:null as unknown,event:null as null|(()=>void)}));
vi.mock('@tauri-apps/api/core',()=>({isTauri:()=>true,convertFileSrc:(p:string)=>`asset://${p}`,invoke:mock.invoke}));
vi.mock('@tauri-apps/api/event',()=>({listen:async(_name:string,fn:()=>void)=>{mock.event=fn;return ()=>{};}}));
vi.mock('@tauri-apps/api/webview',()=>({getCurrentWebview:()=>({onDragDropEvent:async()=>()=>{}})}));
const settings=(quality:number):Settings=>({format:'webp',lossless:false,quality,bitrate:null,vbrQuality:null,effort:2,background:null});
function data(withCandidates=false):Snapshot{return {tools:['test-only fixture'],jobs:[],media:[{id:'source',name:'generated.png',relativeName:'generated.png',bytes:1000,sha256:'fixture-hash',properties:{kind:'image',format:'png',width:32,height:32,alpha:false,bitDepth:8,sampleRate:null,channels:null,duration:null,sampleFormat:null},preview:null,error:null,candidates:withCandidates?[500,1500].map((size,i)=>({id:`candidate-${i}`,mediaId:'source',bytes:size,sha256:`fixture-output-${i}`,settings:[settings(i?100:0)],properties:{kind:'image',format:'webp',width:32,height:32,alpha:false,bitDepth:8,sampleRate:null,channels:null,duration:null,sampleFormat:null},diagnostics:{ssimLight:0.9,ssimDark:0.9,alphaMaxError:0,alphaMeanError:0,pixelIdentical:false,durationDelta:null,notices:['Synthetic GUI test fixture']},preview:null,exported:[]})):[]}]};}
beforeEach(()=>{const storage=new Map<string,string>();vi.stubGlobal("localStorage",{getItem:(k:string)=>storage.get(k)??null,setItem:(k:string,v:string)=>storage.set(k,String(v)),removeItem:(k:string)=>storage.delete(k),clear:()=>storage.clear()});mock.invoke.mockReset();mock.snapshot=data();mock.invoke.mockImplementation(async(name:string)=>{if(name==='snapshot')return structuredClone(mock.snapshot);if(name==='image_preview')return '/test-only.png';if(name==='playback_info')return {id:null,position:0,duration:0,paused:true,volume:1,error:null};if(name==='start_jobs')return ['job'];if(name==='export_candidates')return ['generated-compressed.webp'];});});
afterEach(()=>cleanup());
describe('desktop workflow',()=>{
 it('sends custom endpoint sweeps and retains explicit custom settings',async()=>{render(<App/>);await screen.findByRole('button',{name:/generated.png/});fireEvent.click(screen.getByRole('button',{name:'Advanced'}));fireEvent.change(screen.getByRole('combobox',{name:'Output format'}),{target:{value:'webp'}});fireEvent.change(screen.getByRole('combobox',{name:'Compression type'}),{target:{value:'lossy'}});fireEvent.change(screen.getByRole('textbox',{name:/Study quality settings/}),{target:{value:'0,100'}});fireEvent.click(screen.getByRole('button',{name:/Quick study/}));await waitFor(()=>expect(mock.invoke).toHaveBeenCalledWith('start_jobs',{items:[['source',[settings(0),settings(100)]]]}));expect(JSON.parse(localStorage.getItem('media-compression-settings-v1')!).sweep).toBe('0,100');});
 it('excludes larger results by default but allows deliberately exporting them',async()=>{mock.snapshot=data(true);render(<App/>);const larger=await screen.findByRole('checkbox',{name:'Export WEBP · quality 100'});await waitFor(()=>expect((screen.getByRole('checkbox',{name:'Export WEBP · quality 0'})as HTMLInputElement).checked).toBe(true));expect((larger as HTMLInputElement).checked).toBe(false);fireEvent.click(larger);fireEvent.click(screen.getByRole('button',{name:/Export selected/}));await waitFor(()=>expect(mock.invoke).toHaveBeenCalledWith('export_candidates',{ids:['candidate-0','candidate-1'],report:true}));});
 it('reports a rejected job without a false success status',async()=>{mock.invoke.mockImplementation(async(name:string)=>{if(name==='snapshot')return data();if(name==='image_preview')return '/test-only.png';if(name==='start_jobs')throw Error('Invalid encoder combination');});render(<App/>);await screen.findByRole('button',{name:/generated.png/});fireEvent.click(screen.getByRole('button',{name:/Compress selected/}));await screen.findByRole('alert');expect(screen.queryByText('Compression started. Originals stay unchanged.')).toBeNull();});
});
