// @vitest-environment jsdom
import {StrictMode} from 'react';
import {beforeEach,afterEach,describe,it,expect,vi} from 'vitest';
import {act,cleanup,render,screen,fireEvent,waitFor} from '@testing-library/react';
import type {Snapshot,Settings} from './types';
import App from './App';
const mock=vi.hoisted(()=>({invoke:vi.fn(),snapshot:null as unknown,unlisten:[] as ReturnType<typeof vi.fn>[],event:null as null|(()=>void)}));
vi.mock('@tauri-apps/api/core',()=>({isTauri:()=>true,convertFileSrc:(p:string)=>`asset://${p}`,invoke:mock.invoke}));
vi.mock('@tauri-apps/api/event',()=>({listen:async(_name:string,fn:()=>void)=>{mock.event=fn;const off=vi.fn();mock.unlisten.push(off);return off;}}));
vi.mock('@tauri-apps/api/webview',()=>({getCurrentWebview:()=>({onDragDropEvent:async()=>()=>{}})}));
const settings=(quality:number):Settings=>({format:'webp',lossless:false,quality,bitrate:null,vbrQuality:null,effort:2,background:null});
function data(withCandidates=false):Snapshot{return {tools:['test-only fixture'],jobs:[],media:[{id:'source',name:'generated.png',relativeName:'generated.png',bytes:1000,sha256:'fixture-hash',properties:{kind:'image',format:'png',width:32,height:32,alpha:false,bitDepth:8,sampleRate:null,channels:null,duration:null,sampleFormat:null},preview:null,error:null,candidates:withCandidates?[500,1500].map((size,i)=>({id:`candidate-${i}`,mediaId:'source',bytes:size,sha256:`fixture-output-${i}`,settings:[settings(i?100:0)],properties:{kind:'image',format:'webp',width:32,height:32,alpha:false,bitDepth:8,sampleRate:null,channels:null,duration:null,sampleFormat:null},diagnostics:{ssimLight:0.9,ssimDark:0.9,alphaMaxError:0,alphaMeanError:0,pixelIdentical:false,durationDelta:null,notices:['Synthetic GUI test fixture']},preview:null,exported:[]})):[]}]};}
beforeEach(()=>{const storage=new Map<string,string>();vi.stubGlobal("localStorage",{getItem:(k:string)=>storage.get(k)??null,setItem:(k:string,v:string)=>storage.set(k,String(v)),removeItem:(k:string)=>storage.delete(k),clear:()=>storage.clear()});mock.invoke.mockReset();mock.unlisten=[];mock.snapshot=data();mock.invoke.mockImplementation(async(name:string)=>{if(name==='snapshot')return structuredClone(mock.snapshot);if(name==='image_preview')return '/test-only.png';if(name==='playback_info')return {id:null,position:0,duration:0,paused:true,volume:1,error:null};if(name==='start_jobs')return ['job'];if(name==='export_candidates')return ['generated-compressed.webp'];});});
afterEach(()=>cleanup());
describe('desktop workflow',()=>{
 it('provides folder-scoped agent configuration without clearing the GUI session',async()=>{const original=mock.invoke.getMockImplementation()!;mock.invoke.mockImplementation(async(name:string,...args:unknown[])=>name==='agent_configuration'?{configuration:{mcpServers:{'media-compression':{command:'/bundled/agent',args:['mcp','--root','/selected']}}},cliPath:'/bundled/agent',skillPath:'/bundled/skill.md'}:original(name,...args));render(<App/>);await screen.findByRole('button',{name:/generated.png/});const trigger=screen.getByRole('button',{name:'Agent connection'});fireEvent.click(trigger);expect(screen.getByRole('dialog')).toBeTruthy();fireEvent.click(screen.getByRole('button',{name:'Choose granted folder'}));const config=await screen.findByRole('textbox',{name:'MCP configuration'});await waitFor(()=>expect((config as HTMLTextAreaElement).value).toContain('/selected'));expect(mock.invoke).not.toHaveBeenCalledWith('clear_cache');expect(document.activeElement).toBe(config);(config as HTMLTextAreaElement).blur();fireEvent.keyDown(document,{key:'Tab'});expect(document.activeElement).toBe(screen.getByRole('button',{name:'Close agent connection'}));(document.activeElement as HTMLElement).blur();fireEvent.keyDown(document,{key:'Escape'});expect(screen.queryByRole('dialog')).toBeNull();expect(document.activeElement).toBe(trigger);},30000); // Hosted Windows can spend >5s initializing jsdom accessibility queries.

 it('removes late event subscriptions during strict lifecycle cleanup',async()=>{const view=render(<StrictMode><App/></StrictMode>);await screen.findByRole('button',{name:/generated.png/});await waitFor(()=>expect(mock.unlisten).toHaveLength(2));expect(mock.unlisten[0]).toHaveBeenCalledOnce();view.unmount();expect(mock.unlisten[1]).toHaveBeenCalledOnce();});
 it('clears playback and loops when choosing another source',async()=>{const snapshot=data();snapshot.media=[0,1].map(i=>({...snapshot.media[0],id:`audio-${i}`,name:`audio-${i}.wav`,properties:{...snapshot.media[0].properties!,kind:'audio',format:'wav',channels:1,sampleRate:44100,duration:3}}));mock.snapshot=snapshot;await act(async()=>{render(<App/>);});fireEvent.click(screen.getByRole('button',{name:'Audio'}));await screen.findByRole('button',{name:/audio-0.wav/});const loop=screen.getByRole('checkbox',{name:'Loop'});fireEvent.click(loop);expect((loop as HTMLInputElement).checked).toBe(true);mock.invoke.mockClear();fireEvent.click(screen.getByRole('button',{name:/audio-1.wav/}));await waitFor(()=>expect(mock.invoke).toHaveBeenCalledWith('playback_control',{action:'stop',value:null,end:null}));expect((screen.getByRole('checkbox',{name:'Loop'}) as HTMLInputElement).checked).toBe(false);fireEvent.click(screen.getByRole('checkbox',{name:'Loop'}));fireEvent.click(screen.getByRole('button',{name:'Stop'}));expect((screen.getByRole('checkbox',{name:'Loop'}) as HTMLInputElement).checked).toBe(false);});

 it('shows progress while backend events arrive continuously',async()=>{render(<App/>);await screen.findByRole('button',{name:/generated.png/});mock.snapshot=data(true);const pulse=setInterval(()=>mock.event?.(),10);try{await screen.findByRole('checkbox',{name:'Export WEBP · quality 0'},{timeout:2000});}finally{clearInterval(pulse);}});

 it('sends custom endpoint sweeps and retains explicit custom settings',async()=>{render(<App/>);await screen.findByRole('button',{name:/generated.png/});fireEvent.click(screen.getByRole('button',{name:'Advanced'}));fireEvent.change(screen.getByRole('combobox',{name:'Output format'}),{target:{value:'webp'}});fireEvent.change(screen.getByRole('combobox',{name:'Compression type'}),{target:{value:'lossy'}});fireEvent.change(screen.getByRole('textbox',{name:/Study quality settings/}),{target:{value:'0,100'}});fireEvent.click(screen.getByRole('button',{name:/Quick study/}));await waitFor(()=>expect(mock.invoke).toHaveBeenCalledWith('start_jobs',{items:[['source',[settings(0),settings(100)]]]}));expect(JSON.parse(localStorage.getItem('media-compression-settings-v1')!).sweep).toBe('0,100');});
 it('excludes larger results by default but allows deliberately exporting them',async()=>{mock.snapshot=data(true);render(<App/>);const larger=await screen.findByRole('checkbox',{name:'Export WEBP · quality 100'});await waitFor(()=>expect((screen.getByRole('checkbox',{name:'Export WEBP · quality 0'})as HTMLInputElement).checked).toBe(true));expect((larger as HTMLInputElement).checked).toBe(false);expect(screen.getByText('500 bytes')).toBeTruthy();fireEvent.click(larger);fireEvent.click(screen.getByRole('button',{name:/Export selected/}));await waitFor(()=>expect(mock.invoke).toHaveBeenCalledWith('export_candidates',{ids:['candidate-0','candidate-1'],report:true}));});
 it('selects only verified lossless defaults after a lossless study despite earlier smaller lossy candidates',async()=>{
  mock.snapshot=data(true);const original=mock.invoke.getMockImplementation()!;
  mock.invoke.mockImplementation(async(name:string,...args:unknown[])=>{
   if(name==='start_jobs'){
    const snapshot=data(true),base=snapshot.media[0].candidates[0];
    snapshot.media[0].candidates.push({...base,id:'verified-lossless',bytes:750,settings:[{...settings(80),lossless:true}],diagnostics:{...base.diagnostics,pixelIdentical:true}}, {...base,id:'unverified-lossless',bytes:400,settings:[{...settings(80),lossless:true}]});
    mock.snapshot=snapshot;return ['job'];
   }
   return original(name,...args);
  });
  render(<App/>);const oldLossy=await screen.findByRole('checkbox',{name:'Export WEBP · quality 0'});
  await waitFor(()=>expect((oldLossy as HTMLInputElement).checked).toBe(true));
  fireEvent.change(screen.getByRole('combobox',{name:'Output format'}),{target:{value:'webp'}});
  fireEvent.change(screen.getByRole('combobox',{name:'Compression type'}),{target:{value:'lossless'}});
  fireEvent.click(screen.getByRole('button',{name:/Quick study/}));
  await waitFor(()=>expect(mock.invoke).toHaveBeenCalledWith('start_jobs',{items:[['source',[{...settings(80),lossless:true}]]]}));
  await waitFor(()=>expect(screen.getAllByRole('checkbox',{name:'Export WEBP · lossless'}).map(c=>(c as HTMLInputElement).checked)).toEqual([false,true]));
  expect((oldLossy as HTMLInputElement).checked).toBe(false);
  fireEvent.click(screen.getByRole('button',{name:/Export selected/}));
  await waitFor(()=>expect(mock.invoke).toHaveBeenCalledWith('export_candidates',{ids:['verified-lossless'],report:true}));
 });
 it('reports a rejected job without a false success status',async()=>{mock.invoke.mockImplementation(async(name:string)=>{if(name==='snapshot')return data();if(name==='image_preview')return '/test-only.png';if(name==='start_jobs')throw Error('Invalid encoder combination');});render(<App/>);await screen.findByRole('button',{name:/generated.png/});await waitFor(()=>expect((screen.getByRole('button',{name:/Compress selected/}) as HTMLButtonElement).disabled).toBe(false));fireEvent.click(screen.getByRole('button',{name:/Compress selected/}));await screen.findByRole('alert');expect(screen.queryByText('Compression started. Originals stay unchanged.')).toBeNull();});
});
